Repository jlcarrascof/PF-Henry-Project, pull requests merged in 2024-03, with the labels that each got.

#124 (Rigoberto)prueba para corregir comportamiento negativo por despliegue…
  README.md
Labels: bug

#125 ¡Urgente! Reparación del componente Login
  Client/vite-project/src/components/login/LogValidation.ts
  Client/vite-project/src/components/login/Login.css
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/login/_ ver pero no tocar_Login2.tsx
Labels: bug

#127 (rigoberto)modifico package.json del front con *build: vite build*
  Client/vite-project/package.json
Labels: bug

#131 Searchbar Model Configuration Issue Resolution
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/components/landingPage/LandingPage.tsx
  Client/vite-project/src/components/login/Login.tsx
  server/src/controllers/roomController.js
  server/src/controllers/usersController.js
  server/src/handlers/hotelsHandlers.js
  server/src/handlers/roomHandlers.js
  server/src/handlers/usersHandlers.js
  server/src/models/RoomsModel.js
  server/src/models/UserModel.js
  server/src/routes/roomRouter.js
Labels: bug

#132 Reviews,reset,favorites
  Client/package.json
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/card/Card.css
  Client/vite-project/src/components/cards/Cards.tsx
  Client/vite-project/src/components/cart/CartReservation.tsx
  Client/vite-project/src/components/detail/Detail.tsx
  Client/vite-project/src/components/filters/Filters.tsx
  Client/vite-project/src/components/filters/filters.css
  Client/vite-project/src/components/home/Home.tsx
  Client/vite-project/src/components/landingPage/LandingPage.modules.css
  Client/vite-project/src/components/landingPage/LandingPage.tsx
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/notification system/Notification.tsx
  Client/vite-project/src/components/register/Register.tsx
  Client/vite-project/src/components/reviewForm/reviewForm.tsx
  Client/vite-project/src/components/reviewForm/reviewFormComponent.tsx
  Client/vite-project/src/components/searchBar/SearchBar.module.css
  Client/vite-project/src/components/searchBar/searchbar.css
  server/package.json
  server/src/handlers/roomHandlers.js
  server/src/handlers/usersHandlers.js
  server/src/models/RoomsModel.js
  server/src/routes/roomRouter.js
  server/src/routes/usersRouter.js
Labels: bug

#135 Conflict fix
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/Borrado/BorradoLog.tsx
  Client/vite-project/src/components/home/Home.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/reviewForm/revValidation.ts
  Client/vite-project/src/components/reviewForm/review.css
  Client/vite-project/src/components/reviewForm/reviewForm.tsx
  server/src/handlers/roomHandlers.js
  server/src/models/RoomsModel.js
  server/src/models/TransactionModel.js
Labels: bug

#145 Paginado mica
  Client/vite-project/package.json
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions-types.ts
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/FormRegisterProperty/formHotel/FormHotel.tsx
  Client/vite-project/src/components/FormRegisterProperty/formHotel/HotelValidation.ts
  Client/vite-project/src/components/cart/CartReservation.tsx
  Client/vite-project/src/components/detail/Detail.tsx
  Client/vite-project/src/components/home/Home.tsx
  Client/vite-project/src/components/landingPage/LandingPage.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/pagination/Pagination.tsx
  server/src/handlers/roomHandlers.js
Labels: enhancement

#156 Styles mica
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/FormRegisterProperty/FormRoom/FormRoom.css
  Client/vite-project/src/components/FormRegisterProperty/FormRoom/FormRoom.tsx
  Client/vite-project/src/components/FormRegisterProperty/formHotel/FormHotel.css
  Client/vite-project/src/components/FormRegisterProperty/formHotel/FormHotel.tsx
  Client/vite-project/src/components/cardsLanding/CardsLanding.css
  Client/vite-project/src/components/cart/CartReservation.tsx
  Client/vite-project/src/components/cart/cartReservation.css
  Client/vite-project/src/components/detail/Detail.tsx
  Client/vite-project/src/components/detail/validationReserva.ts
  Client/vite-project/src/components/login/Login.css
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/navBar/navBar.css
  Client/vite-project/src/components/register/RegValidation.ts
  Client/vite-project/src/components/register/Register.modules.css
  Client/vite-project/src/components/register/Register.tsx
  server/src/handlers/usersHandlers.js
  server/src/routes/usersRouter.js
Labels: bug

#158 Rama funcional 2
  Client/vite-project/src/App.tsx
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
Labels: bug

#166 Dashboard for Hotels and Rooms
  Client/vite-project/package.json
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions-types.ts
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/DisableRooms/CardDisable.css
  Client/vite-project/src/components/DisableRooms/CardDisable.tsx
  Client/vite-project/src/components/DisableRooms/CardsDisable.tsx
  Client/vite-project/src/components/DisableRooms/DisableRooms.tsx
  Client/vite-project/src/components/FormRegisterProperty/FormRoom/FormRoom.tsx
  Client/vite-project/src/components/FormRegisterProperty/formHotel/FormHotel.tsx
  Client/vite-project/src/components/FormRegisterProperty/formHotel/HotelValidation.ts
  Client/vite-project/src/components/admin/HotelsDashboard/HotelDashboard.css
  Client/vite-project/src/components/admin/HotelsDashboard/hotelDashboard.tsx
  Client/vite-project/src/components/admin/HotelsDashboard/tableRow.tsx
  Client/vite-project/src/components/cart/CartReservation.tsx
  Client/vite-project/src/components/cart/cartReservation.css
  Client/vite-project/src/components/detail/Detail.tsx
  Client/vite-project/src/components/home/Home.tsx
  Client/vite-project/src/components/landingPage/LandingPage.tsx
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/pagination/Pagination.tsx
  server/src/controllers/adminController.js
  server/src/handlers/adminHandler.js
  server/src/handlers/roomHandlers.js
  server/src/handlers/usersHandlers.js
  server/src/models/UserModel.js
  server/src/routes/adminRouter.js
Labels: enhancement

#180 Mejoras y Correcciones Admin, Reservations, Details, Backend, BDD 🚀🔧
  Client/vite-project/images/Payment-Methods.jpg
  Client/vite-project/package.json
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions-types.ts
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/Redux/Store/store.ts
  Client/vite-project/src/components/Reservations/EmptyComp.tsx
  Client/vite-project/src/components/Reservations/MyReservations.tsx
  Client/vite-project/src/components/admin/HotelsDashboard/HotelDashboard.css
  Client/vite-project/src/components/admin/HotelsDashboard/hotelDashboard.tsx
  Client/vite-project/src/components/admin/HotelsDashboard/tableRow.tsx
  Client/vite-project/src/components/admin/UserDashboard/userDashboardRig.tsx
  Client/vite-project/src/components/admin/utils/ReusableSearchBar.tsx
  Client/vite-project/src/components/admin/utils/calendar.tsx
  Client/vite-project/src/components/admin/utils/popConfirm.tsx
  Client/vite-project/src/components/card/Card.tsx
  Client/vite-project/src/components/cards/Cards.tsx
  Client/vite-project/src/components/detail/Detail.tsx
  Client/vite-project/src/components/detail/detail.css
  Client/vite-project/src/components/favorites/Favorites.tsx
  Client/vite-project/src/components/favorites/FavoritesRooms.tsx
  Client/vite-project/src/components/home/Home.tsx
  Client/vite-project/src/components/landingPage/LandingPage.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  server/src/controllers/adminController.js
  server/src/handlers/adminHandler.js
  server/src/handlers/usersHandlers.js
  server/src/routes/adminRouter.js
  server/src/routes/favRouter.js
  server/src/routes/index.js
  server/src/routes/usersRouter.js
Labels: enhancement

#185 Fixeslocos
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/admin/utils/sideBar.tsx
  Client/vite-project/src/components/cart/cartReservation.css
  Client/vite-project/src/components/dropDown/dropDown.tsx
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/navBar/navBar.css
  Client/vite-project/src/components/register/RegValidation.ts
  Client/vite-project/src/components/register/Register.tsx
  server/src/handlers/usersHandlers.js
  server/src/models/UserModel.js
  server/src/routes/adminRouter.js
  server/src/routes/usersRouter.js
Labels: bug, enhancement

#187 Login arreglado
  Client/vite-project/src/components/admin/UserDashboard/userDashboardRig.tsx
  Client/vite-project/src/components/dropDown/dropDown.tsx
  Client/vite-project/src/components/login/Login.tsx
Labels: bug

#191 Vuelta al axios antiguo
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/landingPage/LandingPage.tsx
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/register/RegValidation.ts
Labels: bug

#201 Completing Dashboard and Linking Components
  Client/vite-project/package.json
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions-types.ts
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/admin/HotelsDashboard/hotelDashboard.tsx
  Client/vite-project/src/components/admin/HotelsDashboard/tableRow.tsx
  Client/vite-project/src/components/admin/UserDashboard/UserDashboard2.tsx
  Client/vite-project/src/components/admin/UserDashboard/userDashboard.tsx
  Client/vite-project/src/components/admin/utils/ConfirmModal.tsx
  Client/vite-project/src/components/admin/utils/sideBar.tsx
  Client/vite-project/src/components/dropDown/dropDown.tsx
  Client/vite-project/src/components/modal/Modal.css
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/userProfile/UserProfile.css
  Client/vite-project/src/components/userProfile/UserProfile.tsx
  Client/vite-project/src/components/userProfile/UserValidation.ts
  server/src/controllers/adminController.js
  server/src/controllers/usersController.js
  server/src/handlers/adminHandler.js
  server/src/handlers/usersHandlers.js
  server/src/models/UserModel.js
  server/src/routes/adminRouter.js
  server/src/routes/usersRouter.js
Labels: bug, enhancement

#210 Pre entrega
  Client/vite-project/package.json
  Client/vite-project/src/App.tsx
  Client/vite-project/src/Redux/Actions/actions.ts
  Client/vite-project/src/Redux/Reducer/reducer.ts
  Client/vite-project/src/components/Reservations/MyReservations.tsx
  Client/vite-project/src/components/Reservations/reviewModal.tsx
  Client/vite-project/src/components/admin/HotelsDashboard/hotelDashboard.tsx
  Client/vite-project/src/components/admin/HotelsDashboard/tableRow.tsx
  Client/vite-project/src/components/admin/UserDashboard/UserDashboard2.tsx
  Client/vite-project/src/components/admin/utils/sideBar.tsx
  Client/vite-project/src/components/card/Card.tsx
  Client/vite-project/src/components/cards/Cards.tsx
  Client/vite-project/src/components/detail/Detail.tsx
  Client/vite-project/src/components/detail/validationReserva.ts
  Client/vite-project/src/components/dropDown/dropDown.tsx
  Client/vite-project/src/components/favorites/FavoritesRooms.tsx
  Client/vite-project/src/components/filters/Filters.tsx
  Client/vite-project/src/components/footer/Footer.tsx
  Client/vite-project/src/components/home/Home.tsx
  Client/vite-project/src/components/login/Login.tsx
  Client/vite-project/src/components/mercadoPago/MercadoPago.tsx
  Client/vite-project/src/components/mercadoPago/Pasarela/Pasarela.css
  Client/vite-project/src/components/mercadoPago/Pasarela/Pasarela.tsx
  Client/vite-project/src/components/mercadoPago/Pasarela/Types.ts
  Client/vite-project/src/components/mercadoPago/Pasarela/TypesPasarelaa.ts
  Client/vite-project/src/components/mercadoPago/pasarela/Pasarela.css
  Client/vite-project/src/components/mercadoPago/pasarela/Pasarela.tsx
  Client/vite-project/src/components/navBar/NavBar.tsx
  Client/vite-project/src/components/register/Register.tsx
  Client/vite-project/src/components/reviewForm/reviewForm.tsx
  Client/vite-project/src/components/reviewForm/reviewFormComponent.tsx
  Client/vite-project/src/components/userProfile/UserProfile.css
  Client/vite-project/src/components/userProfile/UserProfile.tsx
  Client/vite-project/src/components/userProfile/UserValidation.ts
  server/index.js
  server/src/controllers/mercadoPagoController.js
  server/src/handlers/roomHandlers.js
  server/src/handlers/usersHandlers.js
  server/src/models/TransactionModel.js
  server/src/models/UserModel.js
  server/src/routes/index.js
  server/src/routes/mercadoPago.routes.js
  server/src/routes/usersRouter.js
Labels: bug, enhancement
